### ISSUE TITLE
redis的连接地方是否有错误？

### ISSUE THREAD

**Issue by bluefoxah** [oikomi/FishChatServer#2]
刚开始看代码，看到route/server.go第43行是否有误？
需要将Address:cfg.Redis.Port -> Address:cfg.Redis.Addr + cfg.Redis.Port

return &Router{
        cfg:                cfg,
        msgServerClientMap: make(map[string]*libnet.Session),
        sessionStore: storage.NewSessionStore(storage.NewRedisStore(&storage.RedisStoreOptions{
            Network:        "tcp",
            Address:        cfg.Redis.Addr + cfg.Redis.Port,
            ConnectTimeout: time.Duration(cfg.Redis.ConnectTimeout) \* time.Millisecond,
            ReadTimeout:    time.Duration(cfg.Redis.ReadTimeout) \* time.Millisecond,
            WriteTimeout:   time.Duration(cfg.Redis.WriteTimeout) \* time.Millisecond,
            Database:       1,
            KeyPrefix:      base.COMM_PREFIX,
        })),
        topicServerMap: make(map[string]string),
    }

**Comment by oikomi** [comment]
谢谢你  应该是个bug   因为配置的是127.0.0.1 所以这个bug没有复现  稍后修复一下

**Comment by oikomi** [comment]
fixed, see:

https://github.com/oikomi/FishChatServer/commit/dfebb80964ff9619a4c0e791ea15de715ef6df05
