### ISSUE TITLE
顶楼主

### ISSUE THREAD

**Issue by yzk0281** [oikomi/FishChatServer#4]
@miaohonghit 你好，想跟你请教个问题：

顶一下  持续关注学习中~~~

另请问下你这个搭好了怎么测试？

**Comment by yzk0281** [comment]
问下你这个架构的话 并发和性能不知道有没有考虑过

**Comment by oikomi** [comment]
@yzk0281 client下面可以测试   并发和性能每个人都有自己的设计，你可以把自己的理解加进去。分布式系统太灵活，有待线上业务考验。
